# Generated by Django 5.2.1 on 2025-05-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server_side", "0002_borrowtransactions"),
    ]

    operations = [
        migrations.AddField(
            model_name="borrowtransactions",
            name="due_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
